trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    sudo ./start-xvfb.sh
  displayName: Setup Xvfb and Metacity
  workingDirectory: scripts
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'damien-urruty-sonarsource'
    scannerMode: 'Other'
    extraProperties: 'sonar.projectKey=damien-urruty-sonarsource_first-eclipse-plugin'
- task: Maven@3
  displayName: 'Run Maven install'
  env:
    DISPLAY: ":10"
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install -Dsonar.coverage.jacoco.xmlReportPaths=$(Build.Repository.LocalPath)/MyFirstPluginTest/target/site/jacoco-aggregate/jacoco.xml'
    options: '-Pcoverage'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
