trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    sudo ./start-xvfb.sh
  displayName: Setup Xvfb and Metacity
  workingDirectory: scripts
- task: Maven@3
  displayName: 'Run Maven install'
  env:
    DISPLAY: ":10"
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'install'
